### ISSUE TITLE
Generic parameter 'Self' could not be inferred after Kingfisher 5.0 update

### ISSUE THREAD

**Issue by dfmarulanda** [RxSwiftCommunity/RxKingfisher#10]
I recently updated RxKingfisher and Kingfisher to v5. All my previous work is getting 
`Generic parameter 'Self' could not be inferred`
I cannot bind or drive directly to the kf.rx.image()

**Comment by freak4pc** [comment]
Can you provide a reproducible example / project ? 
The example project seems to work fine: https://github.com/RxSwiftCommunity/RxKingfisher/blob/master/Example/Example/ViewController.swift#L73

**Comment by dfmarulanda** [comment]
Yeah. Just changed the driver to observable and the drive to bind(to:) and everything seems working.
