### ISSUE TITLE
Cannot invoke 'bind' with an argument list of type '(to: Binder<Resource?>)'

### ISSUE THREAD

**Issue by phuhk** [RxSwiftCommunity/RxKingfisher#13]
Hi there, I'm just following the doc and receive "Cannot invoke 'bind' with an argument list of type '(to: Binder<Resource?>)'" error. Please help me check if my code have any issue

`viewModel.user.map { user -> NSURL in
       return NSURL.init(string: user.avatar) ?? NSURL.init()
 }
.bind(to: avatarImageView.kf.rx.image())
.disposed(by: rx.disposeBag)`

**Comment by kasyanov-ms** [comment]
`NSURL` doesn't conform to `Resource` type. Use `URL` instead:

```swift
viewModel
    .user
    .map { user in URL(string: user.avatar) }
    .bind(to: avatarImageView.kf.rx.image())
    .disposed(by: rx.disposeBag)
```

**Comment by freak4pc** [comment]
NSURL is deprecated, please use URL instead.

**Comment by dfmarulanda** [comment]
Instance method 'bind(to:)' requires the types 'URL?' and 'Resource?' be equivalent

**Comment by freak4pc** [comment]
I think you have to unwrap your URL.

**Comment by Terriermon** [comment]
Instance method 'bind(to:)' requires the types 'URL' and 'Resource?' be equivalent

**Comment by Terriermon** [comment]
I unwrap the URL but the problem has always existed

**Comment by malonehedges** [comment]
@Terriermon did you ever resolve the issue `Instance method 'bind(to:)' requires the types 'URL' and 'Resource?' be equivalent`
