### ISSUE TITLE
Do not compile because of `Use of undeclared type 'Image'`

### ISSUE THREAD

**Issue by gorbat-o** [RxSwiftCommunity/RxKingfisher#17]
Hi,

This library does not compile since a Kingfisher update I believe.
I replaced the `ImageView` type with `KFCrossPlatformImageView`
and `Image` type with  `KFCrossPlatformImage`

Will it be updated?
I can create a PR for that if needed. (I am testing right now)

**Comment by freak4pc** [comment]
Hey @gorbat-o. See this issue I opened: https://github.com/onevcat/Kingfisher/issues/1303

It seems the maintainer of Kingfisher broke semantic versioning by changing symbol names without bumping a major version, thus breaking this framework. I'll try to take care of this a bit later, I just want to make sure it was only a simple rename and nothing else.

Thanks for reporting this!

**Comment by freak4pc** [comment]
He cut a new minor version, this should be fixed.

**Comment by gorbat-o** [comment]
Awesome, thank you for your quick reply!!
