### ISSUE TITLE
Dependency version conflicts in Carthage

### ISSUE THREAD

**Issue by ttuygun** [RxSwiftCommunity/RxKingfisher#19]
Installing RxKingfisher's 1.0.0 version causes to install RxSwift's 3.0.0.alpha.1 version in Carthage. I  need to remove the RxKingfisher from the Cartfile.

Is anyone experiencing this in Xcode 11.1?

**Comment by freak4pc** [comment]
Cartfile seems to ask for RxSwift 5. I've just checked and it works fine here... not too sure what's the issue you're having. 

https://github.com/RxSwiftCommunity/RxKingfisher/blob/master/Cartfile#L1
