### ISSUE TITLE
RxSwift 6 support

### ISSUE THREAD

**Issue by tareksabry1337** [RxSwiftCommunity/RxKingfisher#24]
Any idea when this is supposed to be up ? Previously in RxSwift 5 the `Reactive` struct didn't have any constraint on its `Base` but in RxSwift 6 however there's a new requirement for `Base` to be AnyObject and `KingfisherWrapper` is a struct therefore incompatible.

**Comment by freak4pc** [comment]
Hey @tareksabry1337,
Usually we cut releases after the final version of RxSwift.
Anyways, I've put on a version on the `rx6` branch. Check it out and let me know if it helps :)
