### ISSUE TITLE
'rx' is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by gorbat-o** [RxSwiftCommunity/RxKingfisher#30]
Hi!

I just recently updated `RxSwift` and `RxKingfisher`.
It seems that some internal changes were made, not sure why this doesn't work anymore.

![image](https://user-images.githubusercontent.com/7542553/116503490-17d90e00-a86b-11eb-9c92-838e09874250.png)

Edit: This PR fixes it -> https://github.com/RxSwiftCommunity/RxKingfisher/pull/28/

**Comment by freak4pc** [comment]
Should be fixed in 2.1.0
