### ISSUE TITLE
Update Cartfile to support Kingfisher v6

### ISSUE THREAD

**Issue by konradholub** [RxSwiftCommunity/RxKingfisher#31]
While Kingfisher 6 is supported since 2.0 version, Cartfile has not been updated since then.
Because of that, the wrong version is being installed. 

Could you please update Cartfile and Cartfile.resolved accordingly?

Thank you in advance

**Comment by ShenYj** [comment]
虽然目前使用并没有什么问题， Kingfisher 已经更新到了 [7.0 的大版本](https://github.com/onevcat/Kingfisher/blob/61f9dba5cdddbf29235091b1172939af47ebd933/Kingfisher.podspec#L4), 而 RxKingFisher最新版本还只支持到 5.0 的大版本，是否该进行一次非必要的升级了

Although there is no problem in use at present, Kingfisher has been updated to [the major version of 7.0](https://github.com/onevcat/Kingfisher/blob/61f9dba5cdddbf29235091b1172939af47ebd933/Kingfisher.podspec#L4), and the latest version of RxKingFisher only supports the major version of 5.0. Is it time to perform an unnecessary upgrade?
