### ISSUE TITLE
Not support with Kingfisher 5

### ISSUE THREAD

**Issue by uypanha** [RxSwiftCommunity/RxKingfisher#8]
I'm currently considering of moving from using Kingfisher 4 to 5, but I found that RxKingfisher only supported till 4. The reason to move is that there is better performance with more customization. I'd love to hear when the update is finally release to supper Kingfisher 5. Thanks

**Comment by freak4pc** [comment]
~~If you open a PR for Kingfisher 5, I wouldn't mind reviewing and approving. Thanks! :)~~

I see there's actually an open PR, I'll take a look at it.

**Comment by freak4pc** [comment]
Fixed in #7. Released RxKingfisher 0.5.0.

**Comment by uypanha** [comment]
@freak4pc thanks for that. 😄
